name: kemppi_ui
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0" # Usa una versiÃ³n estable de Dart

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/Assets/Images/kemppi_logo.png

  fonts:
    - family: Myriad Pro
      fonts:
        - asset: lib/Assets/Fonts/Myriad Pro/MYRIADPRO-REGULAR.OTF
    - family: Proxima Nova
      fonts:
        - asset: lib/Assets/Fonts/Proxima Nova/proximanova_regular.ttf